### ISSUE TITLE
InputSelect constructor from yaml config

### ISSUE THREAD

**Issue by pascalrheaume** [FrancisLab/hass-climate-scheduler#7]
Following update to homeassistant core to InputSelect class (https://github.com/home-assistant/core/commit/b0d033ef29abaf5ef8265d596cdaa3da8c124695) 

self._profile_selector = InputSelect(selector_config)  in [switch.py](https://github.com/FrancisLab/hass-climate-scheduler/blob/22d1ab05f372e620f4a0b028b2ecd22a0475de28/custom_components/climate_scheduler/switch.py#L389) line 389 gives this error: 
File "/usr/src/homeassistant/homeassistant/components/input_select/__init__.py", line 296, in extra_state_attributes
return {ATTR_EDITABLE: self.editable}
AttributeError: 'InputSelect' object has no attribute 'editable'

Fixed it by calling 
self._profile_selector = InputSelect.from_yaml(selector_config)

**Comment by stoyanmarinov** [comment]
This has been bugging me for a while. Thanks for the patch!

**Comment by FrancisLab** [comment]
I've been falling behind on updating my Home Assistant instance lately & had missed this issue. Thanks @pascalrheaume, I'll commit your suggested fix later today.

**Comment by jamesdeeen** [comment]
can you please bump up the hacs version, so that the fix is show as an update inside hacs (current version is v0.1.3 from Jun 15, 2021) 
btw, I love your climate scheduler, it has the best integration into home asstant and is flexible enough to cover all my different heating scenarios. greetings from germany.
thx

**Comment by FrancisLab** [comment]
@jamesdeeen done! Thanks for the good words!
